[build]
  command = "expo export --platform web --dump-sourcemap && node ./sitemap-gen.js"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 404

[functions]
  # Include everything to ensure dynamic routes can be used.
  included_files = ["dist/**/*.html", "dist/_expo/routes.json", "dist/_expo/functions/**/*"]

[[headers]]
  for = "/dist/_expo/functions/*"
  [headers.values]
    # Set to 60 seconds as an example.
    "Cache-Control" = "public, max-age=60, s-maxage=60"